### PR TITLE
add owasp-a9 tag

### PR DESCRIPTION
**Pull request by pethers**
https://github.com/stevespringett/dependency-check-sonar-plugin/issues/83

### CODE REVIEW

**Comment by pethers** [comment]
Don't show up in Security-reports, even with the owasp-a9 tag. But works and new issues get tagged with owasp-a9.

**Comment by Reamer** [comment]
:bulb: This logic is not added sonarqube. It's added in each Plugin. Take a look for example into the java language plugin: https://github.com/SonarSource/sonar-java/blob/220d4a0d7ae2d067ba4978eb72118d3112a5a12f/sonar-java-plugin/src/main/java/org/sonar/plugins/java/JavaRulesDefinition.java#L178
Rule definition: https://github.com/SonarSource/sonar-java/commit/31752985925a130d60a37bac7ce939c450198af2#diff-7ecf99cd2b9faebbe44c4a53e1b94ddeR19

**Comment by pethers** [comment]
Thanks, will test it later tonight.

**Comment by pethers** [comment]
owasp
Works better now, but still missing "Security Hotspots".

**Pull request merged**
